# This is the basic workflow to deploy code live

name: Pipeline

# Controls when the workflow will run
on:
  push:
    branches:
      - master

# This has only one job that is to deploy the code live
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          sftp_only: true
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local_path: "./src/components/"
          remote_path: "/code/gatsby/"
